kind: pipeline
name: default

steps:
- name: django-tests
  image: python
  commands:
    - pip install -r requirements.txt
    - cd dumpert
    - python manage.py test
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: registry-username
    password:
      from_secret: registry-password
    repo: registry.sliceofbits.com/reetenstats
    registry: registry.sliceofbits.com/
    tags: latest
  when:
    branch:
      - master
    event:
      - push