version: "3.7"
services:
#
  db:
    image: postgres:latest
    volumes:
      - reetenstats-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reetenstats
    restart: unless-stopped

  stable_app:
    image: matthijz98/hap-map:latest
    container_name: DumpertStatsDjango
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn reetenstats.wsgi --bind 0.0.0.0:8001 --workers=2"
    depends_on:
      - db
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.reetenstats.rule=Host(`dumpertreeten-stats.nl`)" #$
      - "traefik.http.routers.reetenstats.entrypoints=web-secured" # <== Defining the$
      - "traefik.http.routers.reetenstats.service=reetenstats-service"
      - "traefik.http.routers.reetenstats.tls=true"
      - "traefik.http.routers.reetenstats.tls.certresolver=myresolver"
      - "traefik.http.services.reetenstats-service.loadbalancer.server.port=8001"
    restart: unless-stopped
    environment:
      - DEV=False
      - DEBUG=False
    ports:
      - 8001:8001

  adminer:
    image: adminer
    restart: always

volumes:
  reetenstats-db-data:

