version: "3.7"
services:
#
  db:
    image: postgres:latest
    volumes:
      - ./reetenstats-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: reetenstats
      POSTGRES_PASSWORD: pass # set a password for the database
      POSTGRES_USER: root # set the username for the database

  stable_app:
    build: .
    container_name: DumpertStatsDjango
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn dumpert.wsgi --bind 0.0.0.0:8001 --workers=2"
    depends_on:
      - db
    environment:
      - DEV=True
      - ENABLE_DEBUG=True
      - DB_TYPE=postgressql
      - DB_NAME=reetenstats
      - DB_USER=root
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=pass
    ports:
      - "8001:8001"


