# Generated by Django 3.0.4 on 2020-04-02 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gast_name', models.CharField(max_length=64)),
                ('gast_underline', models.CharField(max_length=64)),
                ('gast_facebook', models.URLField()),
                ('gast_instagram', models.URLField()),
                ('gast_website', models.URLField()),
                ('gast_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_dumpert_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=255)),
                ('show_description', models.TextField()),
                ('show_youtube_id', models.CharField(max_length=32)),
                ('show_dumpert_id', models.CharField(max_length=32)),
                ('show_gasten', models.ManyToManyField(to='reetenstats.Gast')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_ammount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reetenstats.Gast')),
                ('rating_in_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reetenstats.Show')),
                ('rating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reetenstats.RatingType')),
            ],
        ),
    ]
