# Generated by Django 3.0.2 on 2020-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_date',
            field=models.DateField(null=True),
        ),
    ]
