# Generated by Django 3.0.2 on 2020-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0002_show_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gast',
            name='gast_age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gast',
            name='gast_snapchat',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gast',
            name='gast_twitch',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gast',
            name='gast_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gast',
            name='gast_wiki',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gast',
            name='gast_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='gast_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='gast_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='gast_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
