# Generated by Django 3.0.2 on 2020-04-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0004_auto_20200407_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_gasten',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_in_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_in_show', to='reetenstats.Show'),
        ),
    ]
