# Generated by Django 3.0.2 on 2020-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0005_auto_20200414_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_ammount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
