# Generated by Django 3.2.12 on 2022-04-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('reetenstats', '0006_auto_20200421_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtype',
            name='rating_type_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_dumpert_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
