# Generated by Django 3.2.12 on 2022-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0008_auto_20220426_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gast',
            name='gast_underline',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
