# Generated by Django 3.2.12 on 2022-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0010_alter_show_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_dumpert_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_youtube_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
