# Generated by Django 3.2.12 on 2022-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0011_auto_20220506_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_override_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
