# Generated by Django 3.2.12 on 2022-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0012_video_video_override_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_date',
            new_name='show_yt_date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_description',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_title',
        ),
        migrations.AddField(
            model_name='show',
            name='show_dumpert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_dumpert_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_dumpert_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_yt_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_yt_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_yt_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
