# Generated by Django 3.2.12 on 2022-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reetenstats', '0013_auto_20220510_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
